export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECTS_LIST = "GET_PROJECTS_LIST";
export const ADD_INTO_PROJECTS_LIST = "ADD_INTO_PROJECTS_LIST";
export const VALIDATE_FORM_NEW_PROJECT = "VALIDATE_FORM_NEW_PROJECT";
export const SET_CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_TASKS_LIST = "GET_TASKS_LIST";
export const GET_TASKS_LIST_BY_CURRENT_ID_PROJECT =
  "GET_TASKS_LIST_BY_CURRENT_ID_PROJECT";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const VALIDATE_FORM_TASKS = "VALIDATE_FORM_TASKS";
export const DELETE_TASK = "DELETE_TASK";
export const STATE_TASK = "STATE_TASK";
export const CURRENT_TASK = "CURRENT_TASK";
export const EDIT_TASK = "EDIT_TASK";
