export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECTS_LIST = "GET_PROJECTS_LIST";
export const ADD_INTO_PROJECTS_LIST = "ADD_INTO_PROJECTS_LIST";
export const VALIDATE_FORM_NEW_PROJECT = "VALIDATE_FORM_NEW_PROJECT";
export const SET_CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const GET_TASKS_LIST = "GET_TASKS_LIST";
export const GET_TASKS_LIST_BY_CURRENT_ID_PROJECT =
  "GET_TASKS_LIST_BY_CURRENT_ID_PROJECT";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const VALIDATE_FORM_TASKS = "VALIDATE_FORM_TASKS";
